Inicio de clase:

Instalación de paquetes:

```{r message=FALSE, warning=FALSE}
#Instalación

install.packages("dplyr")
install.packages("ggplot2")
install.packages("dslabs")
```

Llamando paquetes:

```{r}
#Llamando los paquetes
library(dplyr)
library(dslabs)
library(ggplot2)

```

Para qué sirve cada paquete

```{r}
?dplyr
?ggplot2
```

Ejemplo de visualización

```{r}

dat <- us_contagious_diseases %>% filter(year == 1967 & disease=="Measles" & count>0 & !is.na(population)) %>%
  mutate(rate = count / population * 10000 * 52 / weeks_reporting)

dat %>% ggplot(aes(state, rate)) +
  geom_bar(stat="identity") +
  coord_flip()
```
Existen datos que se encuentran en librerías como:

```{r}
library(dslabs)
data(us_contagious_diseases)
head(us_contagious_diseases,9)
tail(us_contagious_diseases,3)

data(murders)
head(murders)
max(murders$total)
min(murders$total)
plot(murders$total)

attach(murders)

which.max(total)

detach(murders)

which.max(murders$total)
murders$state[5]

which.min(murders$total)
murders$state[46]
```

